version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: challenge
      POSTGRES_DB: challenge-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql://challenge:challenge@db:5432/challenge-db
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
  
  frontend:
    build:
      context: ./frontend 
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  pgdata:
